version: '3.4'

services:
  scooterbear.gtd:
    image: ${DOCKER_REGISTRY-}scooterbeargtd
    build:
      context: .
      dockerfile: ScooterBear.GTD/Dockerfile
  dynamodb:
    image: "jayroblack/dynamodb-local:1.1"
    ports:
      - "8000:8000"