version: '3.4'

services:
  scooterbear.gtd:
    image: ${DOCKER_REGISTRY-}scooterbeargtd
    build:
      context: .
      dockerfile: ScooterBear.GTD/Dockerfile
# NEED TO FIGURE OUT HOW TO MAKE THIS WORK IN INTEGRATION TEST AND DURING DEV.
#  dynamodb:
#    build:
#      context: .
#      dockerfile: DynamoDbDocker/Dockerfile
#    ports:
#      - "8000:8000"
  identityserver:
    build:
      context: .
      dockerfile: IdentityServerAspNetIdentity/Dockerfile
    ports:
      - "5000:80"