version: '3.4'

services:
  scooterbear.gtd:
    image: ${DOCKER_REGISTRY-}scooterbeargtd
    build:
      context: .
      dockerfile: ScooterBear.GTD/Dockerfile
  dynamodb:
    build:
      context: .
      dockerfile: DynamoDbDocker/Dockerfile
    ports:
      - "8000:8000"