version: '3.4'
# Why run the image?  Because changes to the Dynamo DB schema and the identity server will happen rarely.  Why wait for them to be built every single time?
services:
  dynamodb:  # Run GTDToDo\Externals\IdentityServerAspNetIdentity\BuildIdentityServerAspNetIdentity.sh to create image.
    image: jayroblack/dynamodb-local:1.1
    ports:
      - "8000:8000"