export const GET_OR_CRTEATE_USER = "GET_OR_CRTEATE_USER";
export const LOAD_LABELS = "LOAD_LABELS";

export const LOAD_PROJECTS = "LOAD_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const DELETED_PROJECT = "DELETED_PROJECT";

export const NEWPROJECTDIALOG_OPEN = "newProjectDialog/OPEN";
export const NEWPROJECTDIALOG_CLOSE = "newProjectDialog/CLOSE";
export const NEWPROJECTDIALOG_SAVING = "newProjectDialog/SAVING";
export const NEWPROJECTDIALOG_SAVE_SUCCEEDED = "newProjectDialog/SAVE_SUCCEEDED";
export const NEWPROJECTDIALOG_SAVE_FAILED = "newProjectDialog/SAVE_FAILED";

export const EDIT_PROJECTS_DIALOG_OPEN = "EDIT_PROJECTS_DIALOG_OPEN";
export const EDIT_PROJECTS_DIALOG_CLOSE = "EDIT_PROJECTS_DIALOG_CLOSE";
export const EDIT_PROJECTS_DIALOG_PENDING_RESPONSE = "EDIT_PROJECTS_DIALOG_PENDING_RESPONSE";
export const EDIT_PROJECTS_DIALOG_RESPONSE_SUCCEEDED = "EDIT_PROJECTS_DIALOG_RESPONSE_SUCCEEDED";
export const EDIT_PROJECTS_DIALOG_RESPONSE_FAILED = "EDIT_PROJECTS_DIALOG_RESPONSE_SUCCEEDED";