export const GET_OR_CRTEATE_USER = "GET_OR_CRTEATE_USER";
export const LOAD_LABELS = "LOAD_LABELS";

export const LOAD_PROJECTS = "LOAD_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const DELETED_PROJECT = "DELETED_PROJECT";

export const PROJECT_DIALOG_OPEN = "projectDialog/OPEN";
export const PROJECT_DIALOG_CLOSE = "projectDialog/CLOSE";
export const PROJECT_DIALOG_SAVING = "projectDialog/SAVING";
export const PROJECT_DIALOG_SAVE_SUCCEEDED = "projectDialog/SAVE_SUCCEEDED";
export const PROJECT_DIALOG_SAVE_FAILED = "projectDialog/SAVE_FAILED";

export const EDIT_PROJECTS_DIALOG_OPEN = "EDIT_PROJECTS_DIALOG_OPEN";
export const EDIT_PROJECTS_DIALOG_CLOSE = "EDIT_PROJECTS_DIALOG_CLOSE";
export const EDIT_PROJECTS_DIALOG_PENDING_RESPONSE = "EDIT_PROJECTS_DIALOG_PENDING_RESPONSE";
export const EDIT_PROJECTS_DIALOG_RESPONSE_SUCCEEDED = "EDIT_PROJECTS_DIALOG_RESPONSE_SUCCEEDED";
export const EDIT_PROJECTS_DIALOG_RESPONSE_FAILED = "EDIT_PROJECTS_DIALOG_RESPONSE_SUCCEEDED";

export const SOBRIETY_PROMPT_DIALOG_OPEN = "SOBRIETY_PROMPT_DIALOG_OPEN";
export const SOBRIETY_PROMPT_DIALOG_DISMISS = "SOBRIETY_PROMPT_DIALOG_DISMISS";
export const SOBRIETY_PROMPT_DIALOG_YES = "SOBRIETY_PROMPT_DIALOG_YES";
export const SOBRIETY_PROMPT_DIALOG_NO = "SOBRIETY_PROMPT_DIALOG_NO";